export const dummyData = [
  {
    id: "alzlKGqlBbfz3-U1dJfIJg",
    alias: "sapori-e-delizie-roma-2",
    name: "Sapori e Delizie",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/ymd8t2XpydjOQm-65UEbRQ/o.jpg",
    is_closed: true,
    url: "https://www.yelp.com/biz/sapori-e-delizie-roma-2?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 725,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 41.8949555731952,
      longitude: 12.4988673196126,
    },
    transactions: [],
    price: "€€",
    location: {
      address1: "Via Giovanni Lanza 102",
      address2: null,
      address3: "",
      city: "Rome",
      zip_code: "00184",
      country: "IT",
      state: "RM",
      display_address: ["Via Giovanni Lanza 102", "00184 Rome", "Italy"],
    },
    phone: "+39064875450",
    display_phone: "+39 06 487 5450",
    distance: 1840.4599333007327,
  },
  {
    id: "rLaPNO6TLGJLONJjUPhjSg",
    alias: "al-forno-della-soffitta-roma-2",
    name: "Al Forno della Soffitta",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/xVsiYLev28mOBLW5Nv1q6A/o.jpg",
    is_closed: true,
    url: "https://www.yelp.com/biz/al-forno-della-soffitta-roma-2?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 218,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
      {
        alias: "napoletana",
        title: "Napoletana",
      },
      {
        alias: "roman",
        title: "Roman",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 41.9097565,
      longitude: 12.4983264,
    },
    transactions: [],
    price: "€€",
    location: {
      address1: "Via Piave 62",
      address2: "",
      address3: "",
      city: "Rome",
      zip_code: "00187",
      country: "IT",
      state: "RM",
      display_address: ["Via Piave 62", "00187 Rome", "Italy"],
    },
    phone: "+390642011164",
    display_phone: "+39 06 4201 1164",
    distance: 273.0162269071264,
  },
  {
    id: "913ZaqO7F7sZJjasGhXvaQ",
    alias: "pinsere-roma",
    name: "Pinsere",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/59ncS6GUFpC-eKP8eYkOPA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/pinsere-roma?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 221,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 41.9076607,
      longitude: 12.4979234,
    },
    transactions: [],
    price: "€",
    location: {
      address1: "Via Flavia 98",
      address2: "",
      address3: "",
      city: "Rome",
      zip_code: "00187",
      country: "IT",
      state: "RM",
      display_address: ["Via Flavia 98", "00187 Rome", "Italy"],
    },
    phone: "+390642020924",
    display_phone: "+39 06 4202 0924",
    distance: 480.53354356858364,
  },
  {
    id: "vrJvkpcX4wNfcbtiitV6pQ",
    alias: "pizzeria-san-marco-roma-2",
    name: "Pizzeria San Marco",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/ZdkHtE5TqFUsWsCVvXU2jg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/pizzeria-san-marco-roma-2?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 154,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
      {
        alias: "italian",
        title: "Italian",
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 41.9094426,
      longitude: 12.4911743,
    },
    transactions: [],
    price: "€€",
    location: {
      address1: "Via Sardegna 38D",
      address2: "",
      address3: "",
      city: "Rome",
      zip_code: "00187",
      country: "IT",
      state: "RM",
      display_address: ["Via Sardegna 38D", "00187 Rome", "Italy"],
    },
    phone: "+390642012620",
    display_phone: "+39 06 4201 2620",
    distance: 820.4648729717467,
  },
  {
    id: "1OL1AF7V-JpmDb4K94Bp8w",
    alias: "pizzarium-gabriele-bonci-roma",
    name: "Pizzarium Gabriele Bonci",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/2L1FD9TEHU74ZV6qWHHsAA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/pizzarium-gabriele-bonci-roma?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 530,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 41.906728023571,
      longitude: 12.446591048397,
    },
    transactions: [],
    price: "€",
    location: {
      address1: "Via della Meloria 43",
      address2: "",
      address3: "",
      city: "Rome",
      zip_code: "00136",
      country: "IT",
      state: "RM",
      display_address: ["Via della Meloria 43", "00136 Rome", "Italy"],
    },
    phone: "+390639745416",
    display_phone: "+39 06 3974 5416",
    distance: 4509.550235060132,
  },
  {
    id: "MWWJbLqL8CwdGv7qwtk-SQ",
    alias: "pizzeria-serenella-roma",
    name: "Pizzeria Serenella",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/H-G77muaWBnHI8TtsEhtgg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/pizzeria-serenella-roma?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 25,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
    ],
    rating: 5.0,
    coordinates: {
      latitude: 41.91263,
      longitude: 12.49778,
    },
    transactions: [],
    price: "€",
    location: {
      address1: "Via Salaria 70",
      address2: null,
      address3: null,
      city: "Rome",
      zip_code: "00198",
      country: "IT",
      state: "RM",
      display_address: ["Via Salaria 70", "00198 Rome", "Italy"],
    },
    phone: "+390664781660",
    display_phone: "+39 06 6478 1660",
    distance: 243.03056227204226,
  },
  {
    id: "NOHvG4ipWNsC8AN8nZ5fnA",
    alias: "rifugio-romano-roma",
    name: "Rifugio Romano",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/XH2kn74VbCFtbTEYH22NBQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/rifugio-romano-roma?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 150,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
      {
        alias: "italian",
        title: "Italian",
      },
      {
        alias: "vegan",
        title: "Vegan",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 41.90449,
      longitude: 12.49956,
    },
    transactions: [],
    price: "€€",
    location: {
      address1: "Via Volturno 39",
      address2: null,
      address3: null,
      city: "Rome",
      zip_code: "00185",
      country: "IT",
      state: "RM",
      display_address: ["Via Volturno 39", "00185 Rome", "Italy"],
    },
    phone: "+39064880945",
    display_phone: "+39 06 488 0945",
    distance: 785.0648753456029,
  },
  {
    id: "bksiT65ROo8KYI8nuXzTOA",
    alias: "trieste-roma",
    name: "Trieste",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/fTSLwBVItd9HhBbPSooKvw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/trieste-roma?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 74,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 41.89631,
      longitude: 12.49405,
    },
    transactions: [],
    price: "€",
    location: {
      address1: "Via Urbana 112",
      address2: "",
      address3: "",
      city: "Rome",
      zip_code: "00184",
      country: "IT",
      state: "RM",
      display_address: ["Via Urbana 112", "00184 Rome", "Italy"],
    },
    phone: "+39064815319",
    display_phone: "+39 06 481 5319",
    distance: 1768.1967328504672,
  },
  {
    id: "pkgC2-eY81GKNAEuaxGPPw",
    alias: "la-boccaccia-roma-2",
    name: "La Boccaccia",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/conc0IHtxr18mPq5AwfaLg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/la-boccaccia-roma-2?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 55,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
      {
        alias: "vegetarian",
        title: "Vegetarian",
      },
      {
        alias: "italian",
        title: "Italian",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 41.8947207421648,
      longitude: 12.491677030921,
    },
    transactions: [],
    price: "€",
    location: {
      address1: "Via Leonina 73",
      address2: "",
      address3: "",
      city: "Rome",
      zip_code: "00184",
      country: "IT",
      state: "RM",
      display_address: ["Via Leonina 73", "00184 Rome", "Italy"],
    },
    phone: "+393404551968",
    display_phone: "+39 340 455 1968",
    distance: 2004.9631699609743,
  },
  {
    id: "-dflvFWlAqumkJam0j2hbw",
    alias: "nerone-roma-2",
    name: "Nerone",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/PwPbA6862slfGvNhahtp3g/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/nerone-roma-2?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 32,
    categories: [
      {
        alias: "roman",
        title: "Roman",
      },
      {
        alias: "pizza",
        title: "Pizza",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 41.901086,
      longitude: 12.496879,
    },
    transactions: [],
    location: {
      address1: "Via del Viminale 7A",
      address2: "",
      address3: null,
      city: "Rome",
      zip_code: "00184",
      country: "IT",
      state: "RM",
      display_address: ["Via del Viminale 7A", "00184 Rome", "Italy"],
    },
    phone: "+39064880737",
    display_phone: "+39 06 488 0737",
    distance: 1195.353021288455,
  },
  {
    id: "waVDG5MSbqk197zeiIQKSA",
    alias: "pizzeria-del-secolo-roma-2",
    name: "Pizzeria del Secolo",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/IFog6RQduNi-xQ1Z8SFZyQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/pizzeria-del-secolo-roma-2?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 57,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 41.9045601,
      longitude: 12.5048199,
    },
    transactions: [],
    price: "€",
    location: {
      address1: "Via Palestro 62",
      address2: "",
      address3: "",
      city: "Rome",
      zip_code: "00185",
      country: "IT",
      state: "RM",
      display_address: ["Via Palestro 62", "00185 Rome", "Italy"],
    },
    phone: "+390669300865",
    display_phone: "+39 06 6930 0865",
    distance: 834.5903734191843,
  },
  {
    id: "-LUdDr3ITmyz_uK4iVmtug",
    alias: "fratelli-la-bufala-roma",
    name: "Fratelli La Bufala",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/YL3RwmpXhexJjZL9sD6XDw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/fratelli-la-bufala-roma?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 10,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
      {
        alias: "italian",
        title: "Italian",
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 41.91212,
      longitude: 12.49873,
    },
    transactions: [],
    price: "€€",
    location: {
      address1: "Via Velletri 22",
      address2: "",
      address3: "",
      city: "Rome",
      zip_code: "00198",
      country: "IT",
      state: "RM",
      display_address: ["Via Velletri 22", "00198 Rome", "Italy"],
    },
    phone: "+3906853044696",
    display_phone: "+39 06 8530 44696",
    distance: 174.51350647128513,
  },
  {
    id: "iv5kQMZlgNRFrPpcGpGpjA",
    alias: "forno-campo-de-fiori-roma",
    name: "Forno Campo de' Fiori",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/8cLTVBl3ZUGkhZeS5G8ruQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/forno-campo-de-fiori-roma?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 170,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
      {
        alias: "roman",
        title: "Roman",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 41.89582,
      longitude: 12.47155,
    },
    transactions: [],
    price: "€",
    location: {
      address1: "Piazza Campo de' Fiori 22",
      address2: "",
      address3: null,
      city: "Rome",
      zip_code: "00186",
      country: "IT",
      state: "RM",
      display_address: ["Piazza Campo de' Fiori 22", "00186 Rome", "Italy"],
    },
    phone: "+390668806662",
    display_phone: "+39 06 6880 6662",
    distance: 2968.119102622324,
  },
  {
    id: "Q527HyhZn5LPBOPxC_-RAA",
    alias: "grano-frutta-e-farina-roma",
    name: "Grano Frutta e Farina",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/62n8w3_XB3nwtgsoezzviQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/grano-frutta-e-farina-roma?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 99,
    categories: [
      {
        alias: "bakeries",
        title: "Bakeries",
      },
      {
        alias: "desserts",
        title: "Desserts",
      },
      {
        alias: "pizza",
        title: "Pizza",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 41.9059390476011,
      longitude: 12.4788075355223,
    },
    transactions: [],
    price: "€€",
    location: {
      address1: "Via della Croce 49A",
      address2: "",
      address3: "",
      city: "Rome",
      zip_code: "00187",
      country: "IT",
      state: "RM",
      display_address: ["Via della Croce 49A", "00187 Rome", "Italy"],
    },
    phone: "+39066792461",
    display_phone: "+39 06 679 2461",
    distance: 1913.6829589458728,
  },
  {
    id: "nhlk8duGz0ilQXpnXdEKZQ",
    alias: "fiore-di-zucca-roma",
    name: "Fiore di Zucca",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/Fub0qjplQwXD5ri4iIxaRA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/fiore-di-zucca-roma?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 45,
    categories: [
      {
        alias: "italian",
        title: "Italian",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 41.91781,
      longitude: 12.4953299,
    },
    transactions: [],
    price: "€€",
    location: {
      address1: "Via Gaetano Donizetti 16",
      address2: "",
      address3: "",
      city: "Roma",
      zip_code: "00198",
      country: "IT",
      state: "AG",
      display_address: ["Via Gaetano Donizetti 16", "00198 Roma", "Italy"],
    },
    phone: "+390684242417",
    display_phone: "+39 06 8424 2417",
    distance: 835.8834541856295,
  },
  {
    id: "p2LvL-iayqLxNZGu15HLHA",
    alias: "piccolo-buco-roma",
    name: "Piccolo Buco",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/wqQ6wjsFwTLx-_q95mGbvg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/piccolo-buco-roma?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 166,
    categories: [
      {
        alias: "italian",
        title: "Italian",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 41.90135,
      longitude: 12.48469,
    },
    transactions: [],
    price: "€€",
    location: {
      address1: "Via del Lavatore 91",
      address2: null,
      address3: null,
      city: "Rome",
      zip_code: "00187",
      country: "IT",
      state: "RM",
      display_address: ["Via del Lavatore 91", "00187 Rome", "Italy"],
    },
    phone: "+390669380163",
    display_phone: "+39 06 6938 0163",
    distance: 1744.70106117795,
  },
  {
    id: "yK8fykQe-8JITDECU5Q05A",
    alias: "ristorante-pizzeria-andrea-roma",
    name: "Ristorante Pizzeria Andrea",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/9gJ_oLufPEDLCWHjGXMgEg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/ristorante-pizzeria-andrea-roma?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 9,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
      {
        alias: "tuscan",
        title: "Tuscan",
      },
      {
        alias: "roman",
        title: "Roman",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 41.9073615812719,
      longitude: 12.5000760815766,
    },
    transactions: [],
    location: {
      address1: "Via Castelfidardo 30",
      address2: "",
      address3: null,
      city: "Rome",
      zip_code: "00185",
      country: "IT",
      state: "RM",
      display_address: ["Via Castelfidardo 30", "00185 Rome", "Italy"],
    },
    phone: "+3906486848",
    display_phone: "+39 06 486848",
    distance: 457.6779372362602,
  },
  {
    id: "hIw8WuU_BDIbd1nD-2mrpA",
    alias: "al-39-roma",
    name: "Al 39",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/TQKPGasuYSYZE6HN_EL6rQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/al-39-roma?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 14,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
      {
        alias: "roman",
        title: "Roman",
      },
      {
        alias: "mediterranean",
        title: "Mediterranean",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 41.9056206,
      longitude: 12.5033197,
    },
    transactions: [],
    price: "€€",
    location: {
      address1: "Via Palestro 39A",
      address2: null,
      address3: "",
      city: "Rome",
      zip_code: "00185",
      country: "IT",
      state: "RM",
      display_address: ["Via Palestro 39A", "00185 Rome", "Italy"],
    },
    phone: "+39064441213",
    display_phone: "+39 06 444 1213",
    distance: 688.6253046054709,
  },
  {
    id: "skOI0sKnU8xQOg2QHHtD-A",
    alias: "antica-pizzeria-de-roma-roma",
    name: "Antica Pizzeria de Roma",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/fp20ch2B-R3hhf_CJFg8tg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/antica-pizzeria-de-roma-roma?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 6,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 41.90668,
      longitude: 12.49737,
    },
    transactions: [],
    location: {
      address1: "Via XX Settembre 41",
      address2: "",
      address3: "",
      city: "Rome",
      zip_code: "00187",
      country: "IT",
      state: "RM",
      display_address: ["Via XX Settembre 41", "00187 Rome", "Italy"],
    },
    phone: "+390642010120",
    display_phone: "+39 06 4201 0120",
    distance: 595.405715799093,
  },
  {
    id: "kg0fkmi4Cy5fQ8BPyPRHvg",
    alias: "sfizi-di-pizza-roma",
    name: "Sfizi di pizza",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/kcEVdb_tqWoF6SypomSfTw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/sfizi-di-pizza-roma?adjust_creative=HzWgOXvwHcQpxrN2pLmpzw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HzWgOXvwHcQpxrN2pLmpzw",
    review_count: 12,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 41.8994217,
      longitude: 12.4919004,
    },
    transactions: [],
    price: "€",
    location: {
      address1: "Via Genova 15",
      address2: "",
      address3: "",
      city: "Rome",
      zip_code: "00184",
      country: "IT",
      state: "RM",
      display_address: ["Via Genova 15", "00184 Rome", "Italy"],
    },
    phone: "+390648913993",
    display_phone: "+39 06 4891 3993",
    distance: 1534.324399142348,
  },
];
